# fly.toml app configuration file generated for fullstackopencourse-part3-dark-snowflake-5536 on 2023-12-21T14:18:18-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstackopencourse-part3-dark-snowflake-5536"
primary_region = "gig"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
